DECAF_SOURCES = \
 ../../../common/decaf/interfacelist.cc \
 ../../../common/decaf/attributelist.cc \
 ../../../common/decaf/constantpool.cc \
 ../../../common/decaf/classloader.cc \
 ../../../common/decaf/javastring.cc \
 ../../../common/decaf/javathread.cc \
 ../../../common/decaf/javaobject.cc \
 ../../../common/decaf/methodlist.cc \
 ../../../common/decaf/javaclass.cc \
 ../../../common/decaf/fieldlist.cc \
 ../../../common/decaf/scheduler.cc \
 ../../../common/decaf/javaword.cc \
 ../../../common/decaf/cpentry.cc \
 ../../../common/decaf/istream.cc \
 ../../../common/decaf/frame.cc \
 ../../../common/decaf/dmain.cc \
 ../../../common/decaf/decaf.cc \
 ../../../common/decaf/jvm.cc

DECAF_OBJECTS = \
 interfacelist.o \
 attributelist.o \
 constantpool.o \
 classloader.o \
 javastring.o \
 javathread.o \
 javaobject.o \
 methodlist.o \
 javaclass.o \
 fieldlist.o \
 scheduler.o \
 javaword.o \
 cpentry.o \
 istream.o \
 frame.o \
 dmain.o \
 decaf.o \
 jvm.o

%.o : ../../../common/decaf/%.cc
	$(CC) $(CFLAGS) -c $<
