<?php

/* filesystem characteristics */
$_SITE["portaldir"] = "/home/groups/j/jo/jos/sfWiki.1/portal/";
$_SITE["mirrordir"] = $_SITE["portaldir"] . "htdocs/wiki/";
$_SITE["backupdir"] = $_SITE["portaldir"] . "BACKUP/";
$_SITE["phpcgi"] = "/usr/bin/php";

/* website characteristics */
$_SITE["docrootdir"] = "/debug/";
$_SITE["darkbgcolor"] = "#FFCC66";
$_SITE["lightbgcolor"] = "#FFFFCC";
$_SITE["textcolor"] = "#000000";

$_SITE["linkcolor"] = "#0000FF";

/* Who do I mail with problems, if anyone? */
$_SITE["mailto"] = "jquinn@users.sourceforge.net";


/* database characteristics */
$_SITE["dbhost"] = "moby";
$_SITE["dbuser"] = "jos";
$_SITE["dbpass"] = "bqJgIJI4";
$_SITE["database"] = "jos";
$_SITE["dbtable"] = "josOneWikiThreeTopicsTwo";
$_SITE["dbsessiontable"] = "josOneWikiThreeSessions";
$_SITE["dbusertable"] = "josOneWikiThreeUsers";
$_SITE["dbstattable"] = "josOneWikiThreeStats";

/* CVS characteristics */
$_SITE["cvs_link"] = "cvs.sourceforge.net/cgi-bin/viewcvs.cgi/~checkout~/";
$_SITE["cvs_ctype_default"] = "text/plain";
$_SITE["cvs_ctype_html"] = "text/html";

/* Offsite backup characteristics. */
$_SITE["offsite"] = "/working/JJOS.d/joswikiOne-backup";
$_SITE["target"] = "tmiller@65.0.206.139";

?>
