/*

  org/jos/program2b.impl/BasicParameterList.java
  This program is part of CjOS.

  CjOS is free software: you can redistribute it and/or modify
  it under the terms of the GNU Lesser General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU Lesser General Public License for more details.

  You should have received a copy of the GNU Lesser General Public License
  along with this program.  If not, see <http://www.gnu.org/licenses/>.

  Installation : CjOS Project @ cjos.sourceforge.net
  Generated By : XVCL @ fxvcl.sourceforge.net
  SPC Location : eclipse/org.jos/module/program
  Date Written : GCHII July 27, 1999
  Date Revised : GCHII August 13, 1999
                 Upgraded from release 1a to 1b.
                 Release 1a was developed in
                 com.realignsoft.sourceservlet1a.
  Date Revised : GCHII August 16, 1999
                 Upgraded from version 1b to 1c.
                 Isolated parameter list part of
                 ProgramContext.
  Date Revised : GCHII August 16, 1999
                 Upgraded from version 1c to 1d.
  Date Revised : GCHII November 15, 1999
                 Upgraded from version 1d to 2a.
  Date Revised : GCHII August 17, 2000
                 Upgraded source to include license information.
  Date Revised : GCHII May 9, 2001
                 Upgraded from version 2a to 2b.

 */
package org.jos.program2b.impl;

import java.util.Enumeration;

import org.jos.program2a.ParameterList;

import org.jos.uritool2a.URITool;

/**
 * A basic parameter list provides a list of parameters from a string array; and
 * a list of parameters from a query string.
 */
final class BasicParameterList implements ParameterList {
	// static methods and fields
	private static final String SEPARATOR = "=";

	// instance methods and fields
	/**
	 * Creates a parameter list, with no parameters.
	 */
	BasicParameterList() {
	}

	/**
	 * Parse arguments.
	 */
	public void parseArguments(String v) {
		data = QueryStringTool.getTool().getParameters(v);
	}

	/**
	 * Parse arguments, from a string array.
	 */
	public void parseArguments(String[] v) {
		if (v != null) {
			int iMax = v.length;
			data = new String[iMax];
			System.arraycopy(v, 0, data, 0, iMax);
		}
	}

	/**
	 * Gets a parameter, by index.
	 */
	public String getParameter(int index) {
		if (data == null) {
			return null;
		}

		return data[index];
	}

	/**
	 * Gets a value, by key.
	 */
	public String getValue(String key) {
		if (key == null) {
			return null;
		}

		Enumeration<String> list = getParameters();
		for (;;) {
			if (!list.hasMoreElements()) {
				return null;
			}

			String property = (String) list.nextElement();

			int pos = property.indexOf(SEPARATOR);
			if (pos < 0) {
				continue;
			}

			String name = property.substring(0, pos);

			if (name.equals(key)) {
				// *D! return property.substring(pos + 1);
				return URITool.getTool().decode(property.substring(pos + 1));
			}
		}
	}

	/**
	 * Gets all parameters.
	 */
	@Override
	public Enumeration<String> getParameters() {
		return new ObjectArrayEnumeration(data);
	}

	private String[] data = null;
}
