/*

  org/jos/program2b.impl/ObjectArrayEnumeration.java
  This program is part of CjOS.

  CjOS is free software: you can redistribute it and/or modify
  it under the terms of the GNU Lesser General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU Lesser General Public License for more details.

  You should have received a copy of the GNU Lesser General Public License
  along with this program.  If not, see <http://www.gnu.org/licenses/>.

  Installation : CjOS Project @ cjos.sourceforge.net
  Generated By : XVCL @ fxvcl.sourceforge.net
  SPC Location : eclipse/org.jos/module/program
  Date Written : GCHII July 27, 1999
  Date Revised : GCHII August 13, 1999
                 Upgraded from release 1a to 1b.
                 Release 1a was developed in
                 com.realignsoft.sourceservlet1a.
  Date Revised : GCHII August 16, 1999
                 Upgraded from version 1b to 1c.
                 Isolated parameter list part of
                 ProgramContext.
  Date Revised : GCHII August 16, 1999
                 Upgraded from version 1c to 1d.
  Date Revised : GCHII November 15, 1999
                 Upgraded from version 1d to 2a.
  Date Revised : GCHII August 17, 2000
                 Upgraded source to include license information.
  Date Revised : GCHII May 9, 2001
                 Upgraded from version 2a to 2b.

 */
package org.jos.program2b.impl;

import java.util.Enumeration;
import java.util.NoSuchElementException;

/**
 * A basic enumeration for any object array.
 */
final class ObjectArrayEnumeration implements Enumeration<String> {
	/**
	 * Creates an enumeration.
	 */
	public ObjectArrayEnumeration(String[] v) {
		index = 0;
		list = v;
	}

	/**
	 * Determines if this enumeration has more elements.
	 */
	public boolean hasMoreElements() {
		for (;;) {
			try {
				if (list[index] == null) {
					index++;
					continue;
				}
			} catch (NullPointerException e) {
				return false;
			} catch (ArrayIndexOutOfBoundsException e) {
				return false;
			}

			return true;
		}
	}

	/**
	 * Returns the next element.
	 */
	public String nextElement() {
		if (!hasMoreElements()) {
			throw new NoSuchElementException("" + index);
		}

		return list[index++];
	}

	private String[] list;
	private int index;
}
