/*

  org/jos/program2b.impl/QueryStringTool.java
  This program is part of CjOS.

  CjOS is free software: you can redistribute it and/or modify
  it under the terms of the GNU Lesser General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU Lesser General Public License for more details.

  You should have received a copy of the GNU Lesser General Public License
  along with this program.  If not, see <http://www.gnu.org/licenses/>.

  Installation : CjOS Project @ cjos.sourceforge.net
  Generated By : XVCL @ fxvcl.sourceforge.net
  SPC Location : eclipse/org.jos/module/program
  Date Written : GCHII July 27, 1999
  Date Revised : GCHII August 13, 1999
                 Upgraded from release 1a to 1b.
                 Release 1a was developed in
                 com.realignsoft.sourceservlet1a.
  Date Revised : GCHII August 16, 1999
                 Upgraded from version 1b to 1c.
                 Isolated parameter list part of
                 ProgramContext.
  Date Revised : GCHII August 16, 1999
                 Upgraded from version 1c to 1d.
  Date Revised : GCHII November 15, 1999
                 Upgraded from version 1d to 2a.
  Date Revised : GCHII August 17, 2000
                 Upgraded source to include license information.
  Date Revised : GCHII May 9, 2001
                 Upgraded from version 2a to 2b.

 */
package org.jos.program2b.impl;

/**
 * This tool provides a few utility methods to parse a URI query string.
 */
final class QueryStringTool {
	// static methods and fields
	/**
	 * Parameters in a query string are separates by the amperstand character.
	 */
	private static final String SEPARATOR = "&";

	private static final QueryStringTool tool = new QueryStringTool();

	/**
	 * Gets default tool.
	 */
	static QueryStringTool getTool() {
		return tool;
	}

	// instance methods and fields
	protected QueryStringTool() {
	}

	/**
	 * Convert a parameter list from
	 * 
	 * <PRE>
	 * name-1=value-1
	 * name-2=value-2
	 * name-3=value-3
	 * </PRE>
	 * 
	 * to a query string
	 * 
	 * <PRE>
	 * name-1=value-1&name-2=value-2&name-3=value-3
	 * </PRE>
	 */
	public String getQueryString(String[] v) {
		if (v == null) {
			return null;
		}

		int iMax = v.length;
		StringBuffer buffer = new StringBuffer();
		buffer.append(v[0]);
		for (int i = 1; i < iMax; i++) {
			buffer.append(SEPARATOR + v[i]);
		}
		return buffer.toString();
	}

	/**
	 * Convert a query string from
	 * 
	 * <PRE>
	 * name-1=value-1&name-2=value-2&name-3=value-3
	 * </PRE>
	 * 
	 * to a parameter list
	 * 
	 * <PRE>
	 * name-1=value-1
	 * name-2=value-2
	 * name-3=value-3
	 * </PRE>
	 */
	public String[] getParameters(String v) {
		if (v == null) {
			return null;
		}

		int iMax = 1;
		int pos = -1;
		for (;; iMax++) {
			pos = v.indexOf(SEPARATOR, pos + SEPARATOR.length());
			if (pos < 0) {
				break;
			}
		}

		String[] buf = new String[iMax];
		for (int i = 0; i < iMax; i++) {
			pos = v.indexOf(SEPARATOR);
			if (pos < 0) {
				buf[i] = v;
				break;
			}

			buf[i] = v.substring(0, pos);
			v = v.substring(pos + SEPARATOR.length());
		}

		return buf;
	}
}
