<?php

/* filesystem characteristics */
$_SITE["portaldir"] = "/home/groups/j/jo/jos/sfWiki/portal/";
$_SITE["mirrordir"] = $_SITE["portaldir"] . "htdocs/wiki/";
$_SITE["backupdir"] = $_SITE["portaldir"] . "BACKUP/";
$_SITE["phpcgi"] = "/usr/bin/php";

/* website characteristics */
$_SITE["docrootdir"] = "/";
$_SITE["darkbgcolor"] = "#FFCC66";
$_SITE["lightbgcolor"] = "#FFFFCC";
$_SITE["textcolor"] = "#000000";

$_SITE["linkcolor"] = "#0000FF";

/* database characteristics */
$_SITE["dbhost"] = "moby";
$_SITE["dbuser"] = "jos";
$_SITE["dbpass"] = "bqJgIJI4";
$_SITE["database"] = "jos";
$_SITE["dbtable"] = "josWikiThreeTopics";
$_SITE["dbsessiontable"] = "josWikiThreeSessions";
$_SITE["dbusertable"] = "josWikiThreeUsers";

/* CVS characteristics */
$_SITE["cvs_link"] = "cvs.sourceforge.net/cgi-bin/viewcvs.cgi/~checkout~/";
$_SITE["cvs_ctype_default"] = "text/plain";
$_SITE["cvs_ctype_html"] = "text/html";

/* Offsite backup characteristics. */
$_SITE["offsite_dir"] = "/working/JJOS.d/jos-backup";
$_SITE["offsite_user"] = "tmiller";
$_SITE["offsite_address"] = "24.250.243.245";
$_SITE["offsite_port"] = "";

?>
